export const homeObjOne ={
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Safe Training',
    headLine: 'Unlimited the progress with your effort',
    description: 'We help you ensure employee’s safety through education and an industry-leading , professional intervention. Our team will identify growing opportunities in areas like operational meetings, new hire orientation, and hours of on-the-spot training.',
    buttonLabel: 'More Info',
    imgStart: false,
    img: require('../../images/0001.jpg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo ={
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium Safe Training',
    headLine: 'Unlimited the progress with your effort',
    description: 'We help you ensure employee’s safety through education and an industry-leading , professional intervention. Our team will identify growing opportunities in areas like operational meetings, new hire orientation, and hours of on-the-spot training.',
    buttonLabel: 'More Info',
    imgStart: false,
    img: require('../../images/image004.jpeg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: true,
}

export const homeObjThree ={
    id: 'con',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Safe Training',
    headLine: 'Unlimited the progress with your effort',
    description: 'We help you ensure employee’s safety through education and an industry-leading , professional intervention. Our team will identify growing opportunities in areas like operational meetings, new hire orientation, and hours of on-the-spot training.',
    buttonLabel: 'More Info',
    imgStart: false,
    img: require('../../images/image003.jpg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjFour ={
    id: 'testimonials',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Testimonials',
    headLine: 'Candy Honey ',
    description: 'With your trainig on demant, we can train employes individually  instead of bringing all into a classroom at one time.',
    buttonLabel: "Thank's",
    imgStart: false,
    img: require('../../images/woman1.jpg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: true,
}

