export const homeObjOne ={
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Compliance is the Key',
    headLine: 'Higher Level of Safety Caring',
    description: 'SafeStart Training has the tools you need to save 4me, work more efficiently and keep your workplace compliant with OSHA standards. <strong>Contact us today at 813-549-9053.</strong> We want your workplace to be as safe as you do.',
    buttonLabel: 'Learn more',
    imgStart: false,
    img: require('../../images/0001.jpg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: false,
    path: 'About'
}
export const homeObjTwo ={
    id: 'training',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Compliance is the Key',
    headLine: 'Higher Level of Safety Caring',
    description: 'SafeStart Training has the tools you need to save time, work more efficiently and keep your workplace compliant with OSHA standards. Contact us today at 813-549-9053. We want your workplace to be as safe as you do.',
    buttonLabel: 'More Info',
    imgStart: false,
    img: require('../../images/image004.jpeg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: true,
    path: '/contactus'
}

export const homeObjThree ={
    id: 'con',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Benefits',
    headLine: 'Healthy work environments',
    description: 'OSHA compliance can help you reduce your workers’ compensa4on costs, avoid inspections and eliminate costly fines. It guarantees safety in your workplace safer for your employees. Creating a safety culture for your employees elevates their morale because they sense you care about them.',
    buttonLabel: 'See How',
    imgStart: false,
    img: require('../../images/image003.jpg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: false,
    path: '/contactus'
}

export const homeObjFour ={
    id: 'testimonials',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Testimonials',
    headLine: 'Candy Honey ',
    description: 'With your trainig on demant, we can train employes individually  instead of bringing all into a classroom at one time.',
    buttonLabel: "Thank's",
    imgStart: false,
    img: require('../../images/SVG/testimon.svg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: true,
    path: '/Consoluting'
}

export const homeObjFive ={
    id: 'testimonials',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Testimonials',
    headLine: 'Candy Honey ',
    description: 'With your trainig on demant, we can train employes individually  instead of bringing all into a classroom at one time.',
    buttonLabel: "Thank's",
    imgStart: false,
    img: require('../../images/SVG/testimon.svg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: true,
    path: '/Consulting'
}
export const homeObjSix ={
    id: 'testimonials',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Testimonials',
    headLine: 'Candy Honey ',
    description: 'With your trainig on demant, we can train employes individually  instead of bringing all into a classroom at one time.',
    buttonLabel: "Thank's",
    imgStart: false,
    img: require('../../images/SVG/testimon.svg'),
    alt: 'Esffort',
    dark: true,
    primary: true,
    darkText: true,
    path: 'About'
}
export const AboutMision ={
    id: 'Mision',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Our Mision',
    headLine: 'Behind every great human accomplishment, there is a team.',
    description: 'Our mission is to empower and unleash the potential of our clients teams. By inspiring alignment with core values, we make a difference. We empower individuals to take ownership of their workplace safety and health, becoming more effective andsecure.',
    buttonLabel: "Discover More",
    imgStart: false,
    img: require('../../images/misionpage.jpg'),
    alt: 'Mision-Img',
    dark: true,
    primary: true,
    darkText: true,
    path: '/contactus'
}
export const AboutVision ={
    id: 'Vision',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Our Vision',
    headLine: 'Common Grounds of Caring',
    description: 'Our vision is to be your trusted partner in cultivating a culture of excellence throughout your organization. We equip you with the necessary tools to ensure employee safety, maintain a strong safety record, reduce costs, and prevent OSHA violations',
    buttonLabel: "Tell Me More",
    imgStart: false,
    img: require('../../images/visionpage.jpg'),
    alt: 'Mision-Img',
    dark: true,
    primary: true,
    darkText: false,
    path: '/contactus'
}
export const WeAre ={
    id: 'whoweAre',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Who We Are',
    headLine: 'A reliable ally',
    description: 'At SafeStart Training, our experienced leaders and trusted safety industry relationships set us apart. Our dedicated team of professionals specializes in workplace safety training and consulting for both general and construction industries. Serving the United States and its territories, we prioritize your safety and compliance with the Occupational Safety and Health Act. Our mission is to help you meet those needs effectively.',
    buttonLabel: "Get started",
    imgStart: false,
    img: require('../../images/wearepage.jpg'),
    alt: 'Who we are-Img',
    dark: true,
    primary: true,
    darkText: true,
    path: '/contactus'
}

export const testimonioOne = {
    id: 'testimonialone',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Chelsea Mace',
    headLine: 'Safety Council of Palm Beach County.',
    description: 'Damaris Ovando De Vargas is a knowledgeable instructor with a true passion for keeping employees and businesses safe. She is punctual, patient, thorough and informative. Safety is something she takes seriously and truly enjoys teaching.',
    buttonLabel: "Talk to an expert today",
    imgStart: false,
    img: require('../../images/SVG/testimon.png'),
    alt: 'Testimonial person-Img',
    dark: false,
    primary: false,
    darkText: true,
    path: '/contactus'
}
export const testimonioTwo = {
    id: 'testimonialtwo',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: ' Henry Chavez',
    headLine: ' HGC Framing Owner.',
    description: '“I immediately knew I had a poor safety culture. I needed to implement a safety program that would truly impact our team. SafeStart Training managed our safety program for the last three years, taking this load off our shoulders. I would highly recommend them.',
    buttonLabel: "Talk to an expert today",
    imgStart: false,
    img: require('../../images/SVG/testimon.png'),
    alt: 'testimonial person-Img',
    dark: false,
    primary: false,
    darkText: true,
    path: '/contactus'
}
export const testimonioThree = {
    id: 'testimonialthree',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: ' Prisiliano Mendez',
    headLine: 'Forterra.',
    description: '“SafeStart Training has been great. They are accommodating to our needs and budget, while also doing a great job. Right away, having their safety expertise was a load off our minds. We’ve been a client now since 2009 and our safety culture has been better, our stress is lower, and our employees are safer and happier ever since we started working with SafeStart Training.',
    buttonLabel: "Talk to an expert today",
    imgStart: false,
    img: require('../../images/SVG/testimon.png'),
    alt: 'testimonial person-Img',
    dark: false,
    primary: false,
    darkText: true,
    path: '/contactus'
}